services:
  - type: web
    name: ssafiple-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CORS_ORIGINS
        value: "*" # 추후 Netlify 도메인으로 변경 가능
      - key: OPENAI_API_KEY
        sync: false # Render 콘솔에서 직접 입력
